export const authConstants = {
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_FAIILURE: 'LOGIN_FAIILURE',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGOUT_REQUEST: 'LOGOUT_REQUEST',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};

export const userConstants = {
	USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
	USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
	USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
};

export const catagoryConstants = {
	GET_ALL_CATEGORY_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
	GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
	GET_ALL_CATEGORY_FAILUER: 'GET_ALL_CATEGORY_FAILUER',
};
